---
- name: create dir 'vm'
  file:
    path: "{{ cloud_img_store }}/{{ inventory_hostname }}"
    state: directory
 
- name: create file 'user-data'
  template:
    src: user-data.j2
    dest: "{{ cloud_img_store }}/{{ inventory_hostname }}/user-data"

- name: create file 'meta-data'
  template:
    src: meta-data.j2
    dest: "{{ cloud_img_store }}/{{ inventory_hostname }}/meta-data"
 
- name: create 'cloud-init' image
  shell: cd {{ cloud_img_store }}/{{ inventory_hostname }} && genisoimage -output cloud-init.iso -volid cidata -joliet -r user-data meta-data
